In [1]:
import numpy as np

# Creating a Numpy Array

In [2]:
np.array([1,2,2,3,6])

array([1, 2, 2, 3, 6])

In [3]:
 a = np.array([1,2,3])

In [4]:
b = np.array([[1,3,5],[2,4,6]])

In [5]:
b

array([[1, 3, 5],
       [2, 4, 6]])

#### Checking the Shape/Dimension of the Numpy Object 

In [6]:
b.shape

(2, 3)

#### Checking the type of elements inside the numpy array

In [7]:
b.dtype

dtype('int64')

#### Finding no. of Rows in the object

In [8]:
b.ndim

2

#### Checking class/type of the object

In [9]:
print(type(a))

<class 'numpy.ndarray'>


### Creating a Numpy array with specific range using arange() function.

In [10]:
ab = np.arange(1000)

In [11]:
ab

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [12]:
c = range(1000)

#### Let us see how fast Numpy arrays are compared to normal List

#### We will use the %timeit function to check how much execution time of both. 

In [13]:
%timeit [i**3 for i in c]

257 µs ± 11.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [14]:
%timeit ab**3

4.65 µs ± 128 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [15]:
l2 = range(10000)
l3 = [i**2 for i in range(10000)]

In [16]:
%timeit list(map(lambda x,y: x*y, l2, l3))

1.18 ms ± 22 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [17]:
a1 = np.array(l2)
b1 = np.array(l3)

In [18]:
%timeit a1*b1

11.1 µs ± 352 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


#### Creating an array with start and end values

In [19]:
np.arange(2, 20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

#### Skipping values in range

In [20]:
np.arange(5, 15, 3)

array([ 5,  8, 11, 14])

## Creating Numpy Matrix Objects/ arrays like matrices

#### Numpy has interesting functions to create some various arrays/matrices

In [21]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

#### Creating an Identity Matrix(sometimes ambiguously called a unit matrix, of size n is the n × n square matrix with ones on the main diagonal and zeros elsewhere) 

In [23]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

#### Filling the Matrix with desired values

In [24]:
np.full((3,4),18)

array([[18, 18, 18, 18],
       [18, 18, 18, 18],
       [18, 18, 18, 18]])

#### Convering Float/decimal values into integer values, use dtype function

In [25]:
np.full((3,3), 4.56, dtype = np.int)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

#### Inserting desired Diagonal values, using diag() of Numpy

In [26]:
np.diag([1,2,3,4,5,6])

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

#### Stacking an array using tile() function

In [27]:
a

array([1, 2, 3])

In [28]:
np.tile(a,(3,2))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

### Generating Random values in Numpy

#### function for creating random values is numpy.random.random() , this will always return a random number between 0 and 1.

In [29]:
np.random.random()

0.04246723050457679

#### lets say we want a random value between 2 and 50

In [30]:
50*np.random.random() +2

19.729568792695577

#### Creating Matrix of random values

In [31]:
4*np.random.random((3,3))

array([[3.68960805, 1.0791169 , 1.38358532],
       [1.00617698, 2.68355762, 0.80380049],
       [0.9110073 , 3.5345195 , 1.26175011]])

### Creating an array of some range with specific intervals/ distribution between the values

#### let's take values 1 to 50, but equally distributed into 100 parts,
i.e. between 1 to 50 split the data equally into 100 parts.

In [32]:
np.linspace(1,50,100)

array([ 1.        ,  1.49494949,  1.98989899,  2.48484848,  2.97979798,
        3.47474747,  3.96969697,  4.46464646,  4.95959596,  5.45454545,
        5.94949495,  6.44444444,  6.93939394,  7.43434343,  7.92929293,
        8.42424242,  8.91919192,  9.41414141,  9.90909091, 10.4040404 ,
       10.8989899 , 11.39393939, 11.88888889, 12.38383838, 12.87878788,
       13.37373737, 13.86868687, 14.36363636, 14.85858586, 15.35353535,
       15.84848485, 16.34343434, 16.83838384, 17.33333333, 17.82828283,
       18.32323232, 18.81818182, 19.31313131, 19.80808081, 20.3030303 ,
       20.7979798 , 21.29292929, 21.78787879, 22.28282828, 22.77777778,
       23.27272727, 23.76767677, 24.26262626, 24.75757576, 25.25252525,
       25.74747475, 26.24242424, 26.73737374, 27.23232323, 27.72727273,
       28.22222222, 28.71717172, 29.21212121, 29.70707071, 30.2020202 ,
       30.6969697 , 31.19191919, 31.68686869, 32.18181818, 32.67676768,
       33.17171717, 33.66666667, 34.16161616, 34.65656566, 35.15

#### To check memory being used by an object (in bytes)

In [33]:
a.itemsize

8

### Reshaping a Numpy array object

In [34]:
np.arange(18)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [35]:
np.arange(18).shape

(18,)

#### to change the above objects shape we use the reshape() function

In [36]:
np.arange(18).reshape(2,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

#### the above object is a type of 3D array/ matrix by using reshape

#### to reshape we must know the dimensions beforehand, but if we don't know the dimensions division we can use the technique below, it will automatically do the calculation for us

In [37]:
np.arange(18).reshape(2,3,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

## Trick to reshaping an array (this will be very useful in machine learning algorithms)

In [94]:
b2 = np.arange(1, 10)

In [95]:
b2.shape

(9,)

#### we want to convert this array from 1-dimension to 2-D

In [96]:
b2[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [98]:
b2[:,np.newaxis].shape

(9, 1)

### Accessing elements of a numpy array

In [38]:
a2 = np.array([1,2,3,4,5,6,7,8,9,10,11])

In [39]:
a2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [40]:
a2[5]

6

#### Accessing multiple elements using their indexes

In [41]:
a2[[2,4,7]]

array([3, 5, 8])

In [42]:
a2[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [43]:
a2[2:6]

array([3, 4, 5, 6])

#### Skipping / Hopping over desired indexes

In [44]:
a2[0::2]

array([ 1,  3,  5,  7,  9, 11])

#### Some operations on 2D arrays

In [46]:
a3 = np.array([[1,2,3],[56,93,47],[38,20,72]])

In [47]:
a3

array([[ 1,  2,  3],
       [56, 93, 47],
       [38, 20, 72]])

#### Accessing the elements of a 2D array is same as matrix elements i,j, one thing to note as above here too the indexes for rows and columns start from 0,1,2 likewise, so if we want to access the element 47 from a3, we will do this as follows

In [48]:
a3[1,2]

47

### Logical operations on Numpy arrays

#### find all the numbers greater than 12 in a3

In [49]:
a3 > 12

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [51]:
a3[(a3 > 6) & (a3 < 25)]

array([20])

In [58]:
a == b

array([[ True, False, False],
       [False, False, False]])

### Subsetting a Numpy Array

#### Subsetting is very useful in situations when we don't want to disturb the original data in our objects, let's say we have an numpy array ar1 we assign/copy its data to variable br1. Now if we change or perform some operations on br1, the changes will be reflected back into ar1 also, this is because both objects are pointing to the same memory location. Hence our original data is lost and this might be a problem when we want to retain the original data.

In [52]:
ar1 = np.arange(10)

In [53]:
br1 = ar1

In [54]:
np.shares_memory(ar1, br1)

True

In [55]:
br1 = ar1.copy()

In [56]:
np.shares_memory(ar1, br1)

False

#### Transpose of a Numpy array / Matrix

In [61]:
b

array([[1, 3, 5],
       [2, 4, 6]])

In [60]:
b.T

array([[1, 2],
       [3, 4],
       [5, 6]])

#### Stacking two arrays vertically using vstack function

In [63]:
np.vstack((b, a3))

array([[ 1,  3,  5],
       [ 2,  4,  6],
       [ 1,  2,  3],
       [56, 93, 47],
       [38, 20, 72]])

#### Stacking two or more arrays horizontally using hstack function

In [67]:
np.hstack((a3, a3.T))

array([[ 1,  2,  3,  1, 56, 38],
       [56, 93, 47,  2, 93, 20],
       [38, 20, 72,  3, 47, 72]])

#### Some more mathematical functions

In [68]:
np.sin(a3)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.521551  , -0.94828214,  0.12357312],
       [ 0.29636858,  0.91294525,  0.25382336]])

In [69]:
np.cos(a3)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [ 0.85322011,  0.3174287 , -0.99233547],
       [ 0.95507364,  0.40808206, -0.96725059]])

In [70]:
np.tan(a3)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [-0.61127369, -2.98738626, -0.12452757],
       [ 0.31030966,  2.23716094, -0.26241738]])

In [71]:
np.exp(a3)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [2.09165950e+24, 2.45124554e+40, 2.58131289e+20],
       [3.18559318e+16, 4.85165195e+08, 1.85867175e+31]])

In [72]:
np.sum(a3)

332

### Statistical functions on array (Mean, Median, Standard Deviation, etc)

In [73]:
np.mean(a3)

36.888888888888886

In [74]:
np.median(a3)

38.0

In [75]:
np.std(a3)

31.249691356500517

#### Matrix related functions using linalg package in Numpy

#### finding Determinant and Inverse of a Numpy matrix

In [77]:
np.linalg.det(a3)

-5977.999999999997

In [78]:
np.linalg.inv(a3)

array([[-0.96286383,  0.01405152,  0.0309468 ],
       [ 0.37571094,  0.00702576, -0.02024088],
       [ 0.40381398, -0.00936768,  0.00317832]])

#### finding eigen values

In [79]:
np.linalg.eig(a3)

(array([ -1.01922679, 116.80563507,  50.21359172]),
 array([[-0.86958696,  0.02665787,  0.01032465],
        [ 0.33800069,  0.90422254, -0.7455306 ],
        [ 0.35996397,  0.42622875,  0.66639142]]))

#### Dot product of two Matrices

In [80]:
np.dot(a3, a3.T)

array([[   14,   383,   294],
       [  383, 13994,  7372],
       [  294,  7372,  7028]])

### Convrting datatype of elements

In [81]:
p = np.array([1,1,0], dtype = bool)
r = np.array([0,1,0], dtype = bool)

#### Now performing Logical operations provided by Numpy

In [82]:
np.logical_and(p,r)

array([False,  True, False])

In [83]:
np.logical_or(p,r)

array([ True,  True, False])

In [84]:
np.logical_xor(p,r)

array([ True, False, False])

In [85]:
np.all(p == r)

False

#### Column-wise sum of elements of a matrix

In [87]:
a3

array([[ 1,  2,  3],
       [56, 93, 47],
       [38, 20, 72]])

In [86]:
a3.sum(axis = 0)

array([ 95, 115, 122])

#### Row-wise sum / addition of elements of a matrix

In [88]:
a3.sum(axis = 1)

array([  6, 196, 130])

#### finding max and min values

In [90]:
a3.max()

93

In [91]:
a3.min()

1

#### if we want the indexes of max and min values, then

In [92]:
a3.argmax()

4

In [93]:
a3.argmin()

0

#### Sorting an array

In [100]:
np.sort(a3)

array([[ 1,  2,  3],
       [47, 56, 93],
       [20, 38, 72]])